### ISSUE TITLE
Last byte is never sent

### ISSUE THREAD

**Issue by Khartir** [prolic/HumusStreamResponseSender#16]
In the StreamResponseSender the $length is defined as $rangeEnd - $rangeStart, both for the 'Content-Length' header and for the length of the actual stream. This results in a missing last byte:
A request for the Range 0-499/500 returns only 499 bytes when it should return 500 (the last byte is missing)
See also: [https://tools.ietf.org/html/rfc7233#section-4.2](https://tools.ietf.org/html/rfc7233#section-4.2) Examples on Page 13

Recommended Solution: define $length as $rangeEnd -$rangeStar + 1

**Comment by prolic** [comment]
Wanna provide a PR?

**Comment by prolic** [comment]
released with 0.2, thanks a lot @Khartir
